// export default [
//   {
//     Leaders: [
//       {
//         Name: "Fawwaz Bin Tasneem",
//         Post: "Captain",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohammed Areeb Siddiqui",
//         Post: "Vice-Captain",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohd Athar Zaid",
//         Post: "Team Manager",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//     ],
//   },
//   {
//     TechnicalMembers: [
//       {
//         Name: "Fawwaz Bin Tasneem",
//         Post: "High Voltage Systems",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohammad Areeb Siddiqui",
//         Post: "Power Train",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohammad Arham",
//         Post: "Power Train",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Shazia Wali",
//         Post: "Cooling",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Sana Farooqui",
//         Post: "Cooling",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Zaki Abbas Zaidi",
//         Post: "Low Voltage System",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Yashra Malik",
//         Post: "High Voltage System",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohammad Ayman",
//         Post: "Power Train",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//     ],
//   },
//   {
//     ManagementMmebrs: [
//       {
//         Name: "Mohammad Athar Zaid",
//         Post: "Management",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohd Haris Anwar",
//         Post: "Management",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Abdul Hadi Zeeshan",
//         Post: "Management",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Affan Khan",
//         Post: "Management",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//       {
//         Name: "Mohammad Athar",
//         Post: "Management",
//         LinkedIn: "",
//         Gmail: "",
//         Insta: "",
//         Photo: "",
//       },
//     ],
//   },
// ];
export default [
  {
    Leaders: [
      {
        Name: "Saif Shakeel",
        Post: "Captain",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Mudassir Ali",
        Post: "Vice-Captain",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Yashra Malik",
        Post: "Team Manager",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mustafa Rais",
        Post: "Treasurer",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
  {
    TechnicalMembers: [
      {
        Name: "Haris Mirza",
        Post: "Vehicular Dynamics Lead",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Saad Athar",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Alfaiz Khan",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohd Nazim Umar",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Junaid Warsi",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Adnan Zafar",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Safoora Hafeez",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Affan Khan",
        Post: "Vehicular Dynamics",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
  {
    ManagementMmebrs: [
      {
        Name: "Yashra Malik",
        Post: "Manager",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mustafa Rais",
        Post: "Business Lead",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Abdul Tavvab",
        Post: "",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
      {
        Name: "Mohammad Hamza Siddique",
        Post: "",
        LinkedIn: "",
        Gmail: "",
        Insta: "",
        Photo: "",
      },
    ],
  },
];
