export default [
    {
      First:{
        TeamMembers:[
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"https://cdn.pixabay.com/photo/2016/02/28/12/55/boy-1226964_960_720.jpg",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }
            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"https://cdn.pixabay.com/photo/2016/02/28/12/55/boy-1226964_960_720.jpg",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"https://cdn.pixabay.com/photo/2016/02/28/12/55/boy-1226964_960_720.jpg",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
            {
                Name:"Haisam",
                Department:"Developer",
                Image:"",
                Links:{
                    LinkedIn:"",
                    Insta:"",
                    Twitter:""
                }

            },
        ]
    }
  },
  {
    Second:{
      TeamMembers:[
          {
              Name:"Salman",
              Department:"Developer",
              Image:"https://cdn.pixabay.com/photo/2016/02/28/12/55/boy-1226964_960_720.jpg",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }
          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
      ]
  }
},
{
    Third:{
      TeamMembers:[
          {
              Name:"Taimoor",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }
          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
          {
              Name:"Haisam",
              Department:"Developer",
              Image:"",
              Links:{
                  LinkedIn:"",
                  Insta:"",
                  Twitter:""
              }

          },
      ]
  }
},

]